pickmyapple/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from search import views as search_views
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import absolute_import, unicode_literals

from django.db import models

from wagtail.wagtailcore.models import Page

from market.models import MarketItem


class HomePage(Page):
    def get_context(self, request):
        context = super(HomePage, self).get_context(request)

        context['offers'] = MarketItem.objects.all()
        return context

market/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible

from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailadmin.edit_handlers import PageChooserPanel

@register_snippet
@python_2_unicode_compatible
class MarketItem(models.Model):
    '''
    An item available for trade (or free) on the market place
    '''
    UNITS_PLANTS = 1
    UNITS_KILOGRAMS = 2
    _UNIT_CHOICES = (
        (UNITS_PLANTS, "Individual plants"),
        (UNITS_KILOGRAMS, "Kilograms")
    )

    plant = models.ForeignKey('plants.Plant', related_name='market_offers')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    date_posted = models.DateTimeField(auto_now=True)

    quantity = models.FloatField(
        default=1.0,
        help_text="Quantity of plant offered for the trade",

    )

    quantity_units = models.IntegerField(
        choices=_UNIT_CHOICES,
        help_text="Quantity units for plant offered for trade"
    )

    will_post = models.BooleanField(
        default=False,
        help_text="Designates whether the user is willing to post the item(s)"
    )
    pick_your_own = models.BooleanField(
        default=False,
        help_text="Allow traders to harvest the plant(s) themselves, from your garden"
    )
    is_free = models.BooleanField(
        default=False,
        help_text="Give the item(s) away for free"
    )
    accept_offers = models.BooleanField(
        default=True,
        help_text="Accept offers of any other plant(s)"
    )

    wanted_plant = models.ForeignKey(
        'plants.Plant',
        blank=True,
        null=True,
        help_text="The plant desired in return for the offered crop",
        related_name='market_wanted'
    )

    wanted_quantity = models.FloatField(
        default=1.0,
        help_text="Quantity of plant wanted for the trade",
        blank=True,
        null=True
    )

    wanted_quantity_units = models.CharField(
        max_length=32,
        blank=True,
        null=True,
        choices=_UNIT_CHOICES,
        help_text="The units to be used for the quantity of wanted plants"
    )

    comments = models.TextField(blank=True, null=True)

    panels = [
        PageChooserPanel('plant', 'plants.Plant'),
        FieldPanel('user'),
        FieldPanel('quantity'),
        FieldPanel('quantity_units'),
        FieldPanel('will_post'),
        FieldPanel('pick_your_own'),
        FieldPanel('is_free'),
        FieldPanel('accept_offers'),
        PageChooserPanel('wanted_plant', 'plants.Plant'),
        FieldPanel('wanted_quantity'),
        FieldPanel('wanted_quantity_units'),
        FieldPanel('comments')
    ]

    def __str__(self):
        return "{} - {} - {}".format(self.date_posted.strftime("%Y-%m-%d"), self.plant, self.user)

plants/models.py
from django.db import models

from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, MultiFieldPanel, InlinePanel

class PlantIndex(Page):
    pass

class Plant(Page):
    '''
    Represents a plant of any kind
    '''
    common_name = models.CharField(max_length=64)
    variety = models.CharField(max_length=128)
    description = RichTextField(blank=True, null=True)

    content_panels = Page.content_panels + [
        FieldPanel('common_name'),
        FieldPanel('variety'),
        FieldPanel('description', classname="full"),
    ]

market/views.py
from django.shortcuts import render

# Create your views here.

plants/views.py
from django.shortcuts import render

# Create your views here.

search/views.py
from __future__ import absolute_import, unicode_literals

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from wagtail.wagtailcore.models import Page
from wagtail.wagtailsearch.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

home/templates/home/home_page.html
{% extends "base.html" %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="ui container main">
    <h1 class="ui centered massive header" id="marketplace-header">Marketplace</h1>
    <div class="ui vertical fluid menu" id="marketplace">
        {% for item in offers.all %}
        <div class="link item">
            <div class="ui centered three column grid">
                  <div class="row">
                    <div class="center aligned column">
                        <span><i class="user icon"></i>{{ item.user }}</span>
                    </div>
                    <div class="center aligned  column">
                        <h2 class="ui header">{{ item.plant }}s</h2>
                    </div>
                    <div class="center aligned  column">
                        <span><i class="law icon"></i>{{ item.quantity }} {{item.get_quantity_units_display}}</span>

                    </div>
                </div>
                <div class="row">
                    <div class="center aligned column">
                        {% if item.wanted_plant %}
                        <span><i class="exchange icon"></i> {{ item.wanted_plant }}</span>
                        {% elif item.is_free %}
                        <span><i class="heart icon"></i> Free!</span>
                        {% endif %}
                    </div>
                    <div class="center aligned column">
                        {% if item.will_post %}
                        <span><i class="send icon"></i>Will post</span>
                        {% elif item.pick_your_own %}
                        <span><i class="tree icon"></i>PYO</span>
                        {% endif %}
                    </div>
                    <div class="center aligned column"></div>
                </div>
                <div class="row">
                    <div class="center aligned column">
                    </div>
                    <div class="center aligned column">
                        {% if item.will_post and item.pick_your_own %}
                        <span><i class="tree icon"></i>PYO</span>
                        {% endif %}
                    </div>
                    <div class="center aligned column"></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

pickmyapple/templates/base.html
{% load static wagtailuserbar %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch:700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'semantic.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/pickmyapple.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}" style="background: url('{% static "img/vegg.svg" %}'); background-size: 100%;">
        {% wagtailuserbar %}
        <div class="ui top fixed menu">
            <div class="ui container">
                <a class="item" href="/">Home</a>
                <a class="item">Market</a>
                <a class="item" id="google_login" href='/accounts/google/login'>Login</a>
                <div class="center item">
                    <h3 class="ui header">Pick My Apple</h3>
                </div>
                <div class="right item">
                    <div class="ui input"><input type="text" placeholder="Search..."></div>
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}

        {# Global javascript #}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="{% static 'semantic.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/pickmyapple.js' %}"></script>        

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Search" class="button">
    </form>

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description|safe }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if search_results.has_previous %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
        {% endif %}

        {% if search_results.has_next %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
        {% endif %}
    {% elif search_query %}
        No results found
    {% endif %}
{% endblock %}